var searchData=
[
  ['indexglobalmesh',['indexGlobalMesh',['../_tools_8cpp.html#a0484b8c44b5c9772f7df64605478b78a',1,'indexGlobalMesh(int i, int j, int k, int nx, int ny):&#160;Tools.cpp'],['../_tools_8hpp.html#a0484b8c44b5c9772f7df64605478b78a',1,'indexGlobalMesh(int i, int j, int k, int nx, int ny):&#160;Tools.cpp']]],
  ['init',['init',['../class_advection.html#a2c91d4c75b37df039238f5a425512f12',1,'Advection::init()'],['../class_tumor.html#ab81fc2a97251df4d28e122620f7a8c0f',1,'Tumor::init()']]],
  ['initmpi',['initMpi',['../_simulation_8cpp.html#aebc7d284160ee4d5576d279164b6aa27',1,'initMpi(int argc, char **argv, int &amp;me, int &amp;np, double &amp;tp):&#160;Simulation.cpp'],['../_simulation_8hpp.html#aebc7d284160ee4d5576d279164b6aa27',1,'initMpi(int argc, char **argv, int &amp;me, int &amp;np, double &amp;tp):&#160;Simulation.cpp']]],
  ['initsimulation',['initSimulation',['../_simulation_8cpp.html#affa4e4e6a9427a945ff4616076bf33f4',1,'initSimulation(int me, int np, int &amp;i1, int &amp;im, int &amp;nzLocal, int &amp;sizeLocal, Advection *&amp;advectionStep, VectorXd &amp;P0, double &amp;radius, double &amp;iniVolume, double &amp;volume, Tumor *&amp;tumor, double &amp;tini):&#160;Simulation.cpp'],['../_simulation_8hpp.html#affa4e4e6a9427a945ff4616076bf33f4',1,'initSimulation(int me, int np, int &amp;i1, int &amp;im, int &amp;nzLocal, int &amp;sizeLocal, Advection *&amp;advectionStep, VectorXd &amp;P0, double &amp;radius, double &amp;iniVolume, double &amp;volume, Tumor *&amp;tumor, double &amp;tini):&#160;Simulation.cpp']]],
  ['inverseproblem',['inverseProblem',['../_simulation_8cpp.html#a9a471e1bc258984c2ed7b787319c8f63',1,'inverseProblem(double &amp;t, int me, int i1, int im, int np, double tmax, Tumor *tumor, Advection *advectionStep, double &amp;radius, double &amp;volume, double &amp;volume_prev, double iniVolume, double &amp;tgc, double &amp;tsolveV, double &amp;ttransp, double &amp;tupdateP, double &amp;tupdateM, double &amp;tupdateD, double &amp;twrite):&#160;Simulation.cpp'],['../_simulation_8hpp.html#a9a471e1bc258984c2ed7b787319c8f63',1,'inverseProblem(double &amp;t, int me, int i1, int im, int np, double tmax, Tumor *tumor, Advection *advectionStep, double &amp;radius, double &amp;volume, double &amp;volume_prev, double iniVolume, double &amp;tgc, double &amp;tsolveV, double &amp;ttransp, double &amp;tupdateP, double &amp;tupdateM, double &amp;tupdateD, double &amp;twrite):&#160;Simulation.cpp']]],
  ['inversesimulation',['inverseSimulation',['../_simulation_8cpp.html#a9bb6217b77520374716a84e34372f906',1,'inverseSimulation(double sigma, double &amp;t, int me, int i1, int im, double tmax, Tumor *tumor, Advection *advectionStep, double &amp;radius, double &amp;volume, double &amp;volume_prev, double iniVolume, double &amp;tgc, double &amp;tsolveV, double &amp;ttransp, double &amp;tupdateP, double &amp;tupdateM, double &amp;tupdateD, double &amp;twrite):&#160;Simulation.cpp'],['../_simulation_8hpp.html#a9bb6217b77520374716a84e34372f906',1,'inverseSimulation(double sigma, double &amp;t, int me, int i1, int im, double tmax, Tumor *tumor, Advection *advectionStep, double &amp;radius, double &amp;volume, double &amp;volume_prev, double iniVolume, double &amp;tgc, double &amp;tsolveV, double &amp;ttransp, double &amp;tupdateP, double &amp;tupdateM, double &amp;tupdateD, double &amp;twrite):&#160;Simulation.cpp']]]
];
